version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecommerce
    networks:
      - ecommerce-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # fila
      - "15672:15672"    # dashboard
    networks:
      - ecommerce-net

  ecommerce-app:
    build: .
    container_name: ecommerce-app
    depends_on:
      - mongo
      - rabbitmq
    environment:
      MONGO_URI: "mongodb://mongo:27017"
      RABBITMQ_URI: "amqp://guest:guest@rabbitmq:5672/"
    ports:
      - "8080:8080"
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge